---
#
- name: prepare installation directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ oracle_soa_oracle_home }}"
    - "{{ oracle_soa_inventory_directory }}"

- name: prepare installation response file
  template:
    src: install-soa-11g.rsp.j2
    dest: "{{ oracle_soa_response_file }}"

- name: install soa
  shell: "{{ oracle_soa_installer }} -jreLoc /usr/java/latest -silent -responseFile {{ oracle_soa_response_file }} >> /tmp/soa-installation.log"
  args:
    creates: "{{ oracle_soa_soa_home }}"
