---
#
- name: validate oracle soa version is supported
  fail: "msg='version is not valid (supported versions: [12c])'"
  when: oracle_soa_version is defined and oracle_soa_version != "12c"

- include: "install-{{ oracle_soa_version }}.yml"
