---
#
- name: validate oracle soa 12c release is supported
  fail: "msg='release is not valid (supported versions: [12.2.1])'"
  when: oracle_soa_release is defined and oracle_soa_release != '12.2.1'

- include: prepare-installers-12c.yml

- name: create group
  group: name={{ oracle_soa_os_group }} state=present
- name: create user
  user: name={{ oracle_soa_os_user }} group={{ oracle_soa_os_group }} state=present

- name: prepare installation directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ oracle_soa_os_user }}"
    group: "{{ oracle_soa_os_group }}"
  with_items:
    - "{{ oracle_soa_oracle_home }}"
    - "{{ oracle_soa_inventory_directory }}"

- set_fact:
    oracle_soa_response_file: /tmp/soa-install-12c.rsp

- name: prepare installation response file
  template:
    src: soa-install-12c.rsp.j2
    dest: "{{ oracle_soa_response_file }}"
    owner: "{{ oracle_soa_os_user }}"
    group: "{{ oracle_soa_os_group }}"

- name: prepare oracle inventory parameters
  template:
    src: ora_inst.loc.j2
    dest: "{{ oracle_soa_inventory_file }}"
    owner: "{{ oracle_soa_os_user }}"
    group: "{{ oracle_soa_os_group }}"

- set_fact:
    oracle_soa_jar: fmw_{{ oracle_soa_release }}.0.0_bpm_quickstart.jar

- name: install soa
  shell: "java -jar {{ oracle_soa_jar }} -install -silent -invPtrLoc {{ oracle_soa_inventory_file }} -responseFile {{ oracle_soa_response_file }}"
  args:
    creates: "{{ oracle_soa_oracle_home }}/oraInst.loc"
  become: yes
  become_user: "{{ oracle_soa_os_user }}"
