---
- include: prepare-os.yml
  become: yes
  become_user: root
  tags:
    - prepare_os

# tasks file for oracle-soa
- include: install-soa.yml
  become: yes
  become_user: "{{ oracle_soa_os_user }}"
  tags:
    - install

- include: create-jdev-link.yml
  become: yes
  tags:
    - create_jdev_link
