---
#
- name: validate oracle soa 12c release is supported
  fail: "msg='release is not valid (supported versions: [{{ oracle_soa_12c_releases }}])'"
  when: oracle_soa_release not in oracle_soa_12c_releases

- include: define-installers-12c.yml

- name: evaluate oracle soa 12c {{ oracle_soa_release }} installers
  stat: path="{{ item.path }}" get_checksum=yes
  register: zips
  with_items: "{{ installers }}"

- name: validation zips results
  debug:
    var: zips

- name: validate installation zips exist
  fail: msg="installation zip file {{ item.item.path }} is not present"
  when: not item.stat.exists or not item.stat.isreg
  with_items: "{{ zips.results }}"

- name: validate installation zips checksum
  fail: msg="installation zip file {{ item.item.path }} is not valid"
  when: oracle_soa_checksum_enabled and item.stat.checksum != item.item.checksum
  with_items: "{{ zips.results }}"

- name: "unzip installation files"
  unarchive: src="{{ item.path }}" dest=/tmp copy=no
  with_items: "{{ installers }}"
