---
#
- name: validate oracle soa is installed
  stat: path="{{ oracle_soa_oracle_home }}/soa"
  register: soa_home

- debug:
    msg: "oracle soa is already installed in this {{ oracle_soa_oracle_home }}"
  when: soa_home.stat.exists

- set_fact:
    oracle_soa_already_installed: true
  when: soa_home.stat.exists
